### ISSUE TITLE
Cannot install lwip

### ISSUE THREAD

**Issue by benajaero** [OpenSprites/OpenSprites-next#97]
**Expected behavior**
lwip should install normally
**What actually happens**
I get this error
`In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/MyUser/.nvm/versions/node/v7.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0`

I've rebuilt using `npm rebuild lwip` but still doesn't work. I've set up node-gyp correctly as well as the other dependencies. Is this a problem for you as well?

I think this is a compatibility problem with Node.js 7.6.0
What version are you using?

**Comment by benajaero** [comment]
Fixed. lwip is incompatible with 7.6.0 but works with 6.10.0.
